// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdCdHhM6NTyWDbXrypXAk44MFSMPTJuPU',
    appId: '1:74984151796:android:7bbe3f7fb05b092d8f1ca1',
    messagingSenderId: '74984151796',
    projectId: 'fir-app-2105',
    storageBucket: 'fir-app-2105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRXVMWLueHZ_4ZBSx6tAd9BUELNVoWME',
    appId: '1:74984151796:ios:936188a27162c17b8f1ca1',
    messagingSenderId: '74984151796',
    projectId: 'fir-app-2105',
    storageBucket: 'fir-app-2105.firebasestorage.app',
    iosBundleId: 'com.example.castspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiyFDKPFc5v1P7ZBeV98kvhVcHmT6Vh60',
    appId: '1:74984151796:web:c91c48d0192d3fad8f1ca1',
    messagingSenderId: '74984151796',
    projectId: 'fir-app-2105',
    authDomain: 'fir-app-2105.firebaseapp.com',
    storageBucket: 'fir-app-2105.firebasestorage.app',
    measurementId: 'G-WNFFDGN3KS',
  );
}
